name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, ready_for_review]
    branches: [ main ]
    workflow_dispatch:

jobs:
  build:
    name: SuryakantKumar-CountryPicker
    runs-on: macos-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Build app
      run: xcodebuild clean build test -enableCodeCoverage YES -project Framework/CountryPicker.xcodeproj -scheme Framework -destination 'platform=iOS Simulator,name=iPhone 15' ONLY_ACTIVE_ARCH=YES

    - name: Run Swift Package Tests
      run: swift test --parallel | xcpretty
