name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build app
      run: xcodebuild clean build test -enableCodeCoverage YES -project CountryPicker/Framework/Framework.xcodeproj -scheme Framework -destination 'platform=iOS Simulator,name=iPhone 15' ONLY_ACTIVE_ARCH=YES

    - name: Run tests
      run: xcodebuild -project 'CountryPicker/Framework/Framework.xcodeproj' -scheme 'Framework' -destination 'platform=iOS Simulator,name=iPhone 15' test | xcpretty
   

