name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, ready_for_review]
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: SuryakantKumar-CountryPicker
    runs-on: macos-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Set up Xcode Environment
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.2.0'
        
    - name: Clean Previous Builds
      run: |
        xcodebuild clean -project CountryPicker.xcodeproj \
        -scheme CountryPicker \
        -configuration Release
             
    - name: Build CountryPicker
      run: |
        xcodebuild clean build \
        -project CountryPicker.xcodeproj \
        -scheme CountryPicker \
        -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
        ONLY_ACTIVE_ARCH=YES | xcpretty
        
    - name: Run iOS Unit Tests
      run: |
        xcodebuild test \
        -project CountryPicker.xcodeproj \
        -scheme CountryPickerTests \
        -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
        -enableCodeCoverage YES | xcpretty
